name: Bug Report
description: Report a bug to help us improve Notive
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched the existing issues to make sure this bug has not been reported
          required: true
        - label: I am using the latest version of Notive
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Notive Version
      description: Run `notive --version` or check About dialog
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Installation Method
      description: How did you install Notive?
      options:
        - AppImage
        - .deb (Debian/Ubuntu)
        - .rpm (Fedora/RHEL)
        - Flatpak
        - Snap
        - Built from source
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: Linux Distribution
      description: e.g., Ubuntu 24.04, Fedora 41, Arch Linux
      placeholder: "Ubuntu 24.04"
    validations:
      required: true

  - type: input
    id: desktop
    attributes:
      label: Desktop Environment
      description: e.g., GNOME 47, KDE Plasma 6, XFCE
      placeholder: "GNOME 47"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any relevant logs (run with `RUST_LOG=debug notive` for verbose output)
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
    validations:
      required: false
